### ISSUE TITLE
The quality settings doesn't work

### ISSUE THREAD

**Issue by RoboChimera** [walking-octopus/cathode-tube#1]
So, I added fullscreen support by adding this to qml/Pages/VideoDetails.qml at line 65,
And from this I found a bug, it looks like the quality changes doesn't change

```

                // TODO: Handle fullscreen request
                settings.fullScreenSupportEnabled:true

                onFullScreenRequested: {
                         if(request.toggleOn) {
                                 window.showFullScreen()
                         }
                         else {
                                 window.showNormal()
                         }
                         request.accept()
                 }

```

**Comment by aparatext** [comment]
Hi. I'll look into quality later. It seems to work fine. It works by fetching a video streaming URL through YouTube.js and setting this as a URL in the webview.

Thanks for finishing the fullscreen. I'll test it out later. Thanks for finishing it for me!

It seems you've uploaded this app to OpenStore. I appreciate your interest, but it's not yet done. Many features are not yet implemented and an average user wouldn't see the difference between a WIP and a broken app. It would be best if I retain control over the publishing. Mabe the ownership of the listing can somehow be changed, maybe it can be deleted from OpenStore and reuploaded by me. I really hope I don't come off rude, but it's just not yet finished. Just like shipping unstable patches, this just breaks the UX.

**Comment by RoboChimera** [comment]
Yeah! sure, ill delete it rn!

**Comment by aparatext** [comment]
Thanks! Can you also please open a merge request for that fullscreen fix? Thanks for the help. I hope I didn't sound rude. I'll get back to this app after I finish [Vaults](https://github.com/walking-octopus/vaults-ut). I'm puzzled by this bug since the URLs look right in the browser. Maybe it has something to do with how it updates the data?

**Comment by aparatext** [comment]
I think it's because the layout is still in the frame, and the `window.showFullScreen()` might be upscaling the entire window or the Item containing the WebView. Maybe changing its parent to a different Item that fills the entire screen will help. In general, I have plans to switch to a native video player, leaving the WebView as just a fallback.

**Comment by aparatext** [comment]
After a bit of testing, the bug doesn't seem as serious. YouTube.js falls back to 360p when the selected quality is not available. For some weird reason, it rarely finds a format for 1080p. Later, I'll open an issue for it. As a workaround, I'll remove 1080p from the quality selector until this is fixed.

**Comment by RoboChimera** [comment]
this seems to be fixed.

**Comment by aparatext** [comment]
Does video playback work for you? Sadly, the last YouTube redesign broke the video metadata fetching, resulting in a crash. Maybe the V2 version of the library will help solve this issue, but I might not have time for a migration.

**Comment by RoboChimera** [comment]
yeah it results in a crash, but the split second where it isnt crashed, I can see the video quality actually changes.

**Comment by aparatext** [comment]
> yeah it results in a crash, but the split second where it isnt crashed, I can see the video quality actually changes.

I've made a tiny patch to work around that issue (see #5). Feel free to install the up-to-date version from GitHub Actions.
